import { NextRequest, NextResponse } from "next/server";
import { createRepository, pushFileToRepo } from "@/lib/github/service";

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const { name, description } = body;

    if (!name) {
      return NextResponse.json(
        { error: "Project name is required" },
        { status: 400 }
      );
    }

    // 1. Create Repository
    const repoResult = await createRepository({
      name: name.toLowerCase().replace(/\s+/g, "-"), // Slugify name
      description: description || "Generated by Aether OS",
      private: true,
    });

    if (!repoResult.success || !repoResult.url) {
      return NextResponse.json(
        { error: repoResult.error || "Failed to create repository" },
        { status: 500 }
      );
    }

    // 2. Initialize with basic structure (Optional but recommended)
    // We can push a README or a basic package.json here
    const owner = repoResult.url.split("/").slice(-2, -1)[0]; // Extract owner from URL
    const repoName = repoResult.url.split("/").slice(-1)[0];

    await pushFileToRepo(
      owner,
      repoName,
      "README.md",
      `# ${name}\n\n${description}\n\n> Generated by **Aether OS Autonomous Engine**`,
      "Initial commit by Aether OS"
    );

    return NextResponse.json({
      success: true,
      data: {
        name: repoName,
        url: repoResult.url,
        id: repoResult.id,
      },
    });
  } catch (error: any) {
    console.error("API Error:", error);
    return NextResponse.json(
      { error: "Internal Server Error" },
      { status: 500 }
    );
  }
}
